# Generated by Django 3.1.4 on 2021-01-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='url',
            new_name='advert_url',
        ),
    ]
