# Generated by Django 3.1.4 on 2021-01-13 18:36

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20210113_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images'),
        ),
    ]
