# Generated by Django 3.1.4 on 2020-12-31 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
